### PR TITLE
Take into account query in input url.

### PR DESCRIPTION
**Pull request by fsur**

### CODE REVIEW

**Comment by yashrathi-git** [comment]
What does this fix? Could you give example for some URL

**Comment by fsur** [comment]
Hello Yash,

I was confronted to download this video (and a bunch of others with same
syntax) : https://player.vimeo.com/video/706850404?h=d04473d2d2
The minimal link https://player.vimeo.com/video/706850404 leads to to an
unfound video but the full link leads well to the video.

When analyzing the video's url, I extract all parameters with a regex and
pass them to the requests.get, that's it.

Regards,

**Comment by yashrathi-git** [comment]
Hello @fsur 
This makes the url work. But please could you use [urlparse](https://stackoverflow.com/a/28328919/14883305) to parse the query parameter and get the base url instead of custom regex. As that would probably also handle all the edge cases. 

Thank you

**Comment by yashrathi-git** [comment]
Since I didn't heard back, I did the changes myself. 
Thanks!

**Comment by fsur** [comment]
Hi Yash,

Sorry I have been busy last week. I was going to perform the modification,
but I see in your last email that you did it yourself. Sorry and thanks !

Bye

**Comment by yashrathi-git** [comment]
No worries, I understand, thanks for the PR 
I thought it would be bit inefficient to ask for small changes.

**Pull request closed without merging**
